maneuver:
  build: .
  command: ./script/start
  links:
    # - db
    # - test
    - disque
  volumes_from:
    - data
  volumes:
    - ./:/app
    - ./test/ssh_container/ssh:/root/.ssh
  ports:
    - "3000:3000"

disque:
  image: jobflow/disque
  volumes_from:
    - data

data:
  image: busybox
  volumes:
    - /data

db:
  image: postgres
  ports:
    - "5432:5432"

test:
  build: ./test/ssh_container
  ports:
    - "2222:22"
